const main_title = document.getElementById('main_title')
const sub_title = document.getElementById('sub_title')
const list_wrap = document.getElementById('list_wrap')
console.log(main_title)
console.log(sub_title)
console.log(list_wrap)
//---------------
const container = document.getElementById('container')
const title = document.getElementById('title')
const contents = document.getElementById('contents')
const titleA = title.getElementsByTagName('a')
const contentsA = contents.getElementsByTagName('a')
console.log(container)
console.log(title)
console.log(contents)
console.log(titleA)
console.log(contentsA)